ACD-25-category-create
khicchi/CocoonAccountingApp pull request #13
Opened 2022-02-08 14:04 UTC by AdamB25

2022-02-08 16:09 UTC, owermaiden approved these changes

2022-02-09 05:04 UTC, khicchi requested changes
Dear @AdamB25 can you please close this request and update your local master branch then and merge it to your branch. Then creating a fresh pull request will be more effective.

2022-02-09 17:11 UTC, khicchi approved these changes

2022-02-09 17:13 UTC, AdamB25 commented
Ok I did like this let me try again

On Wed, Feb 9, 2022, 20:11 Hüseyin ***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/khicchi/CocoonAccountingApp/pull/13#pullrequestreview-877796492>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVY3B3K3LKMSPVZDSP4ZWFLU2KN47ANCNFSM5N2RYPBQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2022-02-09 17:50 UTC, merged